### ISSUE TITLE
Can't Import Existings Comics

### ISSUE THREAD

**Issue by dgarciam** [hotio/docker-mylar3#1]
When trying to import comics, the process runs fine until i try to import the results to database. When i try to do that, i get the error: **"DataTables warning: table id=impresults_table - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3"**

I only have 3 comics in the /comic folders with about 10 issues total. 

I get [this](https://pastebin.com/7rnufsL4) in the log file. 

DG.-

**Comment by hotio** [comment]
This is for issues with the container, not for the app which is still under heavy development...
